create table coin_details (
	id 					uuid not null,
	coin_id 			varchar(100) not null,
    symbol 				varchar(100) not null,
    name 				varchar(100) not null,
    image 				varchar(400),
    current_price 		numeric(25, 15) not null,
    market_cap 			numeric(30, 15),
    market_cap_rank 	int,
    fully_diluted_valuation numeric(25, 4),
    total_volume 		numeric(15),
    high_24h 			numeric(25, 15),
    low_24h 			numeric(25, 15),
    price_change_24h 	numeric(25, 15),
    price_change_percentage_24h numeric(25, 15),
    market_cap_change_24h numeric(25, 15),
    market_cap_change_percentage_24h numeric(25, 15),
    circulating_supply 	NUMERIC(25),
    total_supply 		NUMERIC(25),
    max_supply 			NUMERIC(25),
    ath 				numeric(25, 15),
    ath_change_percentage numeric(25, 15),
    ath_date 			TIMESTAMP,
    atl 				numeric(25, 15),
    atl_change_percentage numeric(25, 15),
    atl_date 			TIMESTAMP,
    roi 				numeric(25, 15),
    last_updated 		TIMESTAMP not null,
);
